server:
  port: "8000"

client:
  url: "http://localhost:8000"

postgreDatabase:
  host: "localhost"
  port: "5432"
  username: "postgres"
  dbname:  "postgres"
  sslmode: "disable"

redisDatabase:
  port: "6379"

kraken:
  apiurl: "https://demo-futures.kraken.com"